/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pagesRouteRouteImport } from './routes/(pages)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as pagesProductsRouteImport } from './routes/(pages)/products'
import { Route as pagesDashboardRouteImport } from './routes/(pages)/dashboard'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const pagesRouteRoute = pagesRouteRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesProductsRoute = pagesProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesDashboardRoute = pagesDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => pagesRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/dashboard': typeof pagesDashboardRoute
  '/products': typeof pagesProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/dashboard': typeof pagesDashboardRoute
  '/products': typeof pagesProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(pages)': typeof pagesRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(pages)/dashboard': typeof pagesDashboardRoute
  '/(pages)/products': typeof pagesProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/products'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/products'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(pages)'
    | '/(auth)/login'
    | '/(pages)/dashboard'
    | '/(pages)/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  pagesRouteRoute: typeof pagesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pages)': {
      id: '/(pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/products': {
      id: '/(pages)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof pagesProductsRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/dashboard': {
      id: '/(pages)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof pagesDashboardRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface pagesRouteRouteChildren {
  pagesDashboardRoute: typeof pagesDashboardRoute
  pagesProductsRoute: typeof pagesProductsRoute
}

const pagesRouteRouteChildren: pagesRouteRouteChildren = {
  pagesDashboardRoute: pagesDashboardRoute,
  pagesProductsRoute: pagesProductsRoute,
}

const pagesRouteRouteWithChildren = pagesRouteRoute._addFileChildren(
  pagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  pagesRouteRoute: pagesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
