/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as pagesRouteRouteImport } from './routes/(pages)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as pagesUsersRouteImport } from './routes/(pages)/users'
import { Route as pagesSuppliersRouteImport } from './routes/(pages)/suppliers'
import { Route as pagesStockMovementsRouteImport } from './routes/(pages)/stock-movements'
import { Route as pagesReportsRouteImport } from './routes/(pages)/reports'
import { Route as pagesPurchasesRouteImport } from './routes/(pages)/purchases'
import { Route as pagesProductsRouteImport } from './routes/(pages)/products'
import { Route as pagesOrdersRouteImport } from './routes/(pages)/orders'
import { Route as pagesExpensesRouteImport } from './routes/(pages)/expenses'
import { Route as pagesDashboardRouteImport } from './routes/(pages)/dashboard'
import { Route as pagesCustomersRouteImport } from './routes/(pages)/customers'
import { Route as pagesCategoriesRouteImport } from './routes/(pages)/categories'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const pagesRouteRoute = pagesRouteRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesUsersRoute = pagesUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesSuppliersRoute = pagesSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesStockMovementsRoute = pagesStockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesReportsRoute = pagesReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesPurchasesRoute = pagesPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesProductsRoute = pagesProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesOrdersRoute = pagesOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesExpensesRoute = pagesExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesDashboardRoute = pagesDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesCustomersRoute = pagesCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesCategoriesRoute = pagesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => pagesRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/categories': typeof pagesCategoriesRoute
  '/customers': typeof pagesCustomersRoute
  '/dashboard': typeof pagesDashboardRoute
  '/expenses': typeof pagesExpensesRoute
  '/orders': typeof pagesOrdersRoute
  '/products': typeof pagesProductsRoute
  '/purchases': typeof pagesPurchasesRoute
  '/reports': typeof pagesReportsRoute
  '/stock-movements': typeof pagesStockMovementsRoute
  '/suppliers': typeof pagesSuppliersRoute
  '/users': typeof pagesUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/categories': typeof pagesCategoriesRoute
  '/customers': typeof pagesCustomersRoute
  '/dashboard': typeof pagesDashboardRoute
  '/expenses': typeof pagesExpensesRoute
  '/orders': typeof pagesOrdersRoute
  '/products': typeof pagesProductsRoute
  '/purchases': typeof pagesPurchasesRoute
  '/reports': typeof pagesReportsRoute
  '/stock-movements': typeof pagesStockMovementsRoute
  '/suppliers': typeof pagesSuppliersRoute
  '/users': typeof pagesUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(pages)': typeof pagesRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(pages)/categories': typeof pagesCategoriesRoute
  '/(pages)/customers': typeof pagesCustomersRoute
  '/(pages)/dashboard': typeof pagesDashboardRoute
  '/(pages)/expenses': typeof pagesExpensesRoute
  '/(pages)/orders': typeof pagesOrdersRoute
  '/(pages)/products': typeof pagesProductsRoute
  '/(pages)/purchases': typeof pagesPurchasesRoute
  '/(pages)/reports': typeof pagesReportsRoute
  '/(pages)/stock-movements': typeof pagesStockMovementsRoute
  '/(pages)/suppliers': typeof pagesSuppliersRoute
  '/(pages)/users': typeof pagesUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/stock-movements'
    | '/suppliers'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/orders'
    | '/products'
    | '/purchases'
    | '/reports'
    | '/stock-movements'
    | '/suppliers'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(pages)'
    | '/(auth)/login'
    | '/(pages)/categories'
    | '/(pages)/customers'
    | '/(pages)/dashboard'
    | '/(pages)/expenses'
    | '/(pages)/orders'
    | '/(pages)/products'
    | '/(pages)/purchases'
    | '/(pages)/reports'
    | '/(pages)/stock-movements'
    | '/(pages)/suppliers'
    | '/(pages)/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  pagesRouteRoute: typeof pagesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(pages)': {
      id: '/(pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/users': {
      id: '/(pages)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof pagesUsersRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/suppliers': {
      id: '/(pages)/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof pagesSuppliersRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/stock-movements': {
      id: '/(pages)/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof pagesStockMovementsRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/reports': {
      id: '/(pages)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof pagesReportsRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/purchases': {
      id: '/(pages)/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof pagesPurchasesRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/products': {
      id: '/(pages)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof pagesProductsRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/orders': {
      id: '/(pages)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof pagesOrdersRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/expenses': {
      id: '/(pages)/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof pagesExpensesRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/dashboard': {
      id: '/(pages)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof pagesDashboardRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/customers': {
      id: '/(pages)/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof pagesCustomersRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/categories': {
      id: '/(pages)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof pagesCategoriesRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface pagesRouteRouteChildren {
  pagesCategoriesRoute: typeof pagesCategoriesRoute
  pagesCustomersRoute: typeof pagesCustomersRoute
  pagesDashboardRoute: typeof pagesDashboardRoute
  pagesExpensesRoute: typeof pagesExpensesRoute
  pagesOrdersRoute: typeof pagesOrdersRoute
  pagesProductsRoute: typeof pagesProductsRoute
  pagesPurchasesRoute: typeof pagesPurchasesRoute
  pagesReportsRoute: typeof pagesReportsRoute
  pagesStockMovementsRoute: typeof pagesStockMovementsRoute
  pagesSuppliersRoute: typeof pagesSuppliersRoute
  pagesUsersRoute: typeof pagesUsersRoute
}

const pagesRouteRouteChildren: pagesRouteRouteChildren = {
  pagesCategoriesRoute: pagesCategoriesRoute,
  pagesCustomersRoute: pagesCustomersRoute,
  pagesDashboardRoute: pagesDashboardRoute,
  pagesExpensesRoute: pagesExpensesRoute,
  pagesOrdersRoute: pagesOrdersRoute,
  pagesProductsRoute: pagesProductsRoute,
  pagesPurchasesRoute: pagesPurchasesRoute,
  pagesReportsRoute: pagesReportsRoute,
  pagesStockMovementsRoute: pagesStockMovementsRoute,
  pagesSuppliersRoute: pagesSuppliersRoute,
  pagesUsersRoute: pagesUsersRoute,
}

const pagesRouteRouteWithChildren = pagesRouteRoute._addFileChildren(
  pagesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  pagesRouteRoute: pagesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
